---
title: "Metabolites report for `r DrugInterest()`"
date: "`r Sys.Date()`"
header-includes:
- \usepackage{float}
- \usepackage[table]{xcolor}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{pdflscape}
output: 
  pdf_document:
---

`r input$comment`

```{r setup, echo=F}
knitr::opts_chunk$set(echo = TRUE)
if(!"pacman" %in% installed.packages()) install.packages("pacman")
pacman::p_load("cowplot", "readr", "gridExtra", "tinytex", "grid", "png", "rsvg")

suppressMessages(library(kableExtra))
options(knitr.kable.NA = '')

```

<!-- Première page -->

## Positive mode
```{r positive, echo=FALSE}
selected_tab = FullTable()[sort(input$table_rows_selected), ]

if(any(grepl("Positive", selected_tab$Polarity))){
  selected_tab %>% 
    filter(Polarity == "Positive mode") %>%
    select("Formula", "m/z", "RT", "Transformation", "Delta m/z (ppm)", "Intensity", "Score") %>% 
    knitr::kable(
      format = "latex",
      booktabs = TRUE,
      longtable = TRUE,
      linesep = "",
      align = "c"
      ) %>%
    kableExtra::kable_styling(
        position = "center",
        latex_options = c("striped", "repeat_header"),
        stripe_color = "gray!15",
        font_size = 10
      ) 
}


```

## Negative mode
```{r negative, echo=FALSE}

if(any(grepl("Negative", selected_tab$Polarity))){
  selected_tab %>% 
    filter(Polarity == "Negative mode") %>%
    select("Formula", "m/z", "RT", "Transformation", "Delta m/z (ppm)", "Intensity", "Score") %>% 
    knitr::kable(
      format = "latex",
      booktabs = TRUE,
      longtable = TRUE,
      linesep = "",
      align = "c"
      ) %>%
    kableExtra::kable_styling(
        position = "center",
        latex_options = c("striped", "repeat_header"),
        stripe_color = "gray!15",
        font_size = 10
      ) 
}
```

\newpage
```{r content, echo=FALSE, fig.height=10, fig.width=10, results='asis'}

for(metabo in 1:nrow(selected_tab)){
  metabo_pol = ifelse(selected_tab$Polarity[metabo]=="Positive mode", "plus", "minus")
  # Select the image file
  filename = list.files(path(), recursive = T, pattern = paste0("^", selected_tab$Formula[metabo], "_", selected_tab$Index[metabo], "_"))
  
  if(length(filename) > 1) filename = grep(metabo_pol, filename, value=T)
  
  # Display image
  grid.arrange(rasterGrob(readPNG(rsvg_png(file.path(path(), filename), height = 1000, width = 1000))) )
  
  # Select the table file
  tabname = list.files(path(), recursive = T, pattern = paste0("table_", selected_tab$Formula[metabo], "_", selected_tab$Index[metabo], "_"))
  
  if(length(tabname) > 1) tabname = grep(metabo_pol, tabname, value=T)
  
  if(length(tabname) == 1){
    tab_match = read_tsv(file.path(path(), tabname), col_types = cols()) 
    tab_match = tab_match %>% filter(transfo!="No match")
    if(nrow(tab_match) > 0){
      num_cols = names(Filter(is.numeric, tab_match))
      tab_match[num_cols] = tab_match %>% Filter(f=is.numeric) %>% round(4)
      
      # Display the figure and the table of MS2 match, if it exists
      
      print(kable_styling(
              kable(tab_match, 
                format = "latex",
                booktabs = TRUE,
                longtable = TRUE,
                linesep = "",
                align = "ccccccccc"),
              position = "center",
              latex_options = c("striped", "repeat_header"),
              stripe_color = "gray!15"
      ))
    }
  }
  
}
```
